version: "3.8"
services:
    database:
        container_name: postgresql-db
        image: postgres:13.0
        ports:
            - "5432:5432"
        volumes:
            - ./sql-schema.sql:/docker-entrypoint-initdb.d/sql-schema.sql
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mypassword
    web:
        container_name: protocoller
        build: .
        ports:
            - "8082:8082"
        volumes:
            - .:/opt/project
        depends_on:
            - database
        external_links:
            - database